# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'RxSwift-1.0' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-1.0
  pod 'RxSwift', '~> 4.0'

end
